### ISSUE TITLE
Use jtex to render the LaTeX from templates

### ISSUE THREAD

**Issue by leouieda** [compgeolab/paper-template#2]
We were using normal latex variables to insert authors, number and units, etc into different documents for preprints and submission. [jtex[(https://github.com/curvenote/jtex) would let us do that using Jinja templates and adding things from a yaml file. With the yaml file in particularinstead of writing the latex variables in the code, we can put them in a dict and export to yaml then render into the document with Jinja. This last bit would probably require some patches to jtex to allow multiple yaml files and render template the context LaTeX file before rendering the full template.

**Comment by stevejpurves** [comment]
@leouieda happy to patch and alter the cli to accomodate this -- let me know once you have a picture of what you need

**Comment by leouieda** [comment]
Great! I'll be updating this template in the near future and may experiment with jtex a bit if there is time.

**Comment by leouieda** [comment]
Giving up on this for a simpler setup.
